// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcRpxix76niXOuG4cq1c5c7B_pscmKFY',
    appId: '1:117804250485:web:19e8b10e49add6166e4f3c',
    messagingSenderId: '117804250485',
    projectId: 'note-it-c1684',
    authDomain: 'note-it-c1684.firebaseapp.com',
    storageBucket: 'note-it-c1684.firebasestorage.app',
    measurementId: 'G-M035Z940F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngNm1Xy_bi9j9zST-hdwvJiLLjJ220xM',
    appId: '1:117804250485:android:e9c86f42b96f314c6e4f3c',
    messagingSenderId: '117804250485',
    projectId: 'note-it-c1684',
    storageBucket: 'note-it-c1684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-gDkt3MUzT_SRsJwTtE4-0jlMiI7oSo',
    appId: '1:117804250485:ios:feb5cbbc6f5d38406e4f3c',
    messagingSenderId: '117804250485',
    projectId: 'note-it-c1684',
    storageBucket: 'note-it-c1684.firebasestorage.app',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-gDkt3MUzT_SRsJwTtE4-0jlMiI7oSo',
    appId: '1:117804250485:ios:feb5cbbc6f5d38406e4f3c',
    messagingSenderId: '117804250485',
    projectId: 'note-it-c1684',
    storageBucket: 'note-it-c1684.firebasestorage.app',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhcRpxix76niXOuG4cq1c5c7B_pscmKFY',
    appId: '1:117804250485:web:708d7795374e63056e4f3c',
    messagingSenderId: '117804250485',
    projectId: 'note-it-c1684',
    authDomain: 'note-it-c1684.firebaseapp.com',
    storageBucket: 'note-it-c1684.firebasestorage.app',
    measurementId: 'G-FCN2SRTR1L',
  );
}
